# =============================================================================
# test_sjis_corpus_combos.py
# =============================================================================
# assets/glyphs/corpus/aahub_aa003_train.sjis_combos.v1.json is generated by
# scripts/sjis_corpus_combos.py from AAHub training slugs of a pinned
# ascii-art-archive snapshot. These tests check the tracked file's contract
# and the viewer loader without the archive or the font:
#   - identities are pinned (archive commit, split, font) and training-only;
#   - every rendered combination carries '#'/'.' rows for itself and its mirror;
#   - the 15.5 mirror table maps as the skill states and is an involution
#     on the swap pairs;
#   - `glyph_families_viewer.py --mode sjis --dump` shows every rendered entry.
# Nothing here is a runtime claim. The file is offline review data.
#
# Run with:
#     python3 -m pytest scripts/tests/test_sjis_corpus_combos.py -q
# =============================================================================
from __future__ import annotations

import json
import subprocess
import sys
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "scripts"))

import sjis_corpus_combos as scc  # noqa: E402

DATA = ROOT / "assets/glyphs/corpus/aahub_aa003_train.sjis_combos.v1.json"


class TrackedDataset(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.d = json.loads(DATA.read_text(encoding="utf-8"))

    def test_identities_are_pinned_and_training_only(self) -> None:
        d = self.d
        self.assertEqual(d["schema"], "sjis_corpus_combos.v1")
        self.assertEqual(d["archive_commit"], "3687cc564d3f542a3aaaea98b351713b360599f4")
        self.assertEqual(d["split_sha256"], "d61d856f26b0fd019797e6f5756bce0cc76249618c482962a14c364919a8d500")
        self.assertEqual(d["font_sha256"], "8f8c9b6ebe65f12456c3fa42ccddc4ec4795aad8b7f0a12f00d9f09f31a35890")
        self.assertEqual(d["partition"], "train")
        self.assertEqual(d["pages"], 23363)
        self.assertEqual(len(d["per_slug"]), d["slugs"])

    def test_rendered_entries_have_rows_and_mirrors(self) -> None:
        cats = {v["category"] for v in self.d["viewable"]}
        self.assertEqual(cats, {"idiom", "bigram", "trigram", "stack", "band"})
        for v in self.d["viewable"]:
            for key in ("rows", "mirror_rows"):
                self.assertTrue(v[key], (v["key"], key))
                self.assertTrue(all(set(r) <= {"#", "."} for r in v[key]), v["key"])
                self.assertTrue(any("#" in r for r in v[key]), (v["key"], key))
            if v["category"] in ("bigram", "trigram"):
                self.assertGreater(len(set(v["key"])), 1, "a one-glyph repeat is not a combination")

    def test_outline_lists_exclude_pure_tone(self) -> None:
        for e in self.d["bigrams_outline"] + self.d["trigrams_outline"]:
            self.assertTrue(scc.is_outline(e["g"]), e["g"])


class MirrorTable(unittest.TestCase):
    def test_skill_swap_pairs(self) -> None:
        self.assertEqual(scc.mirror("⌒ヽ"), ("ノ⌒", True))
        self.assertEqual(scc.mirror("／￣"), ("￣＼", True))
        self.assertEqual(scc.mirror("(_"), ("_)", True))
        for a, b in (("ヽ", "ノ"), ("(", ")"), ("（", "）"), ("／", "＼"), ("/", "\\"), ("｀", "´")):
            self.assertEqual(scc.MIRROR[a], b)
            self.assertEqual(scc.MIRROR[b], a)

    def test_unknown_asymmetric_glyph_is_flagged(self) -> None:
        self.assertFalse(scc.mirror("ゝ_")[1])


class ViewerLoader(unittest.TestCase):
    def test_sjis_axis_dumps_every_rendered_entry(self) -> None:
        n = len(json.loads(DATA.read_text(encoding="utf-8"))["viewable"])
        out = subprocess.run([sys.executable, str(ROOT / "scripts/glyph_families_viewer.py"),
                              "--mode", "sjis", "--dump"], capture_output=True, text=True, check=True).stdout
        self.assertIn(f"families={n}", out)
        self.assertIn("⌒ヽ  mirror ノ⌒", out)


if __name__ == "__main__":
    unittest.main()
